// Generated by CoffeeScript 1.12.6

/*
============================
Register the Service Worker
============================
 */

(function() {
  var button;

  navigator.serviceWorker.register('./sw.js');


  /*
  ============================
  Instant Gratification/ Testing
  ============================
   */

  button = document.getElementById('test-notification');

  button.addEventListener('click', function() {
    return Notification.requestPermission(function() {
      return navigator.serviceWorker.ready.then(function(registration) {
        var options;
        options = {
          body: 'shake yo hands, stretch those thighs, take a walk, get some water, take a break',
          icon: '/media/grow.png',
          badge: '/media/grow.png',
          silent: true
        };
        return registration.active.postMessage({
          title: 'Move dat body',
          options: options
        });
      });
    });
  });


  /*
  ============================
  45 minute interval pushes
  ============================
   */

  window.setInterval(function() {
    return Notification.requestPermission(function() {
      return navigator.serviceWorker.ready.then(function(registration) {
        var options;
        options = {
          body: 'shake yo hands, stretch those thighs, take a walk, get some water, take a break',
          icon: '/media/grow.png',
          badge: '/media/grow.png',
          silent: true
        };
        return registration.active.postMessage({
          title: 'Move dat Body',
          options: options
        });
      });
    });
  }, 2.7e+6);

}).call(this);
