// Generated by CoffeeScript 1.12.6

/*
====================
Third-Party Modules
====================
 */

(function() {
  var app, bodyParser, express, path, port, request;

  express = require('express');

  bodyParser = require('body-parser');

  path = require('path');

  request = require('request');

  require('dotenv-safe').load();


  /*
  ====================
  App Setup
  ====================
   */

  app = express();

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(bodyParser.json());

  port = process.env.PORT;


  /*
  ====================
  Routing
  ====================
   */

  app.get('/', function(req, res) {
    return res.sendFile(path.join(__dirname + '/index.html'));
  });


  /*
  ====================
  Register Routes
  ====================
   */

  app.use("/", express["static"](__dirname + '/'));


  /*
  ====================
  Run Server
  ====================
   */

  app.listen(port, function() {
    return console.log("Notifications currently running on localhost: " + port + ".");
  });

}).call(this);
