// Generated by CoffeeScript 1.12.6
(function() {
  self.addEventListener('install', function() {
    return self.skipWaiting();
  });

  self.addEventListener('activate', function() {
    return self.clients.claim();
  });

  self.addEventListener('message', function(event) {
    var options, title;
    title = event.data.title;
    options = event.data.options;
    return self.registration.showNotification(title, options);
  });

  self.addEventListener('notificationclick', function(e) {
    var notification;
    notification = e.notification;
    console.log("Clicked on", notification.title);
    return notification.close();
  });

}).call(this);
